name: CI

on:
  push:
    branches: [ master ]

jobs:
  main:
    name: Deploy to functions
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - run: npm run build --if-present
    - name: Deploy to Firebase
      uses: BIGG-Kaymo/deploy-firebase-functions@v1.0.1
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
